help:
	@echo "Usage: make <target>"
	@echo "Targets:"
	@echo "  migrate-dev-up: Run migrations up"
	@echo "  migrate-dev-down: Run migrations down"
	@echo "  migrate-dev-reset: Run migrations reset"
	@echo "  migrate-dev-drop: Run migrations drop"
	@echo "  migrate-dev-create: Create a new migration"
	@echo "  dev-docker-drop-db: Drop the database in the docker container"
	@echo "  dev-docker-create-db: Create the database in the docker container"
	@echo "  dev-create-db: Create the database"
	@echo "  dev-drop-db: Drop the database"
	@echo "  build: Build the application"
	@echo "  run: Run the application"
	@echo "  client: Run the client"

migrate-dev-up:
	migrate -path ./migrations -database "postgres://postgres:123456@localhost:5432/module_service_db?sslmode=disable" up

migrate-dev-down:
	migrate -path ./migrations -database "postgres://postgres:123456@localhost:5432/module_service_db?sslmode=disable" down

migrate-dev-reset:
	migrate -path ./migrations -database "postgres://postgres:123456@localhost:5432/module_service_db?sslmode=disable" reset

migrate-dev-drop:
	migrate -path ./migrations -database "postgres://postgres:123456@localhost:5432/module_service_db?sslmode=disable" drop

migrate-dev-create:
	migrate create -ext sql -dir ./migrations -seq $(name)

dev-docker-drop-db:
	docker exec -it postgres_container dropdb --force -U postgres module_service_db

dev-docker-create-db:
	docker exec -it postgres_container createdb -U postgres module_service_db

dev-create-db:
	createdb -U postgres module_service_db

dev-drop-db:
	dropdb -U postgres module_service_db

build:
	go build -o app cmd/main.go

run:
	go run cmd/main.go

client:
	go run cmd/client/main.go