migrate-dev-up:
	migrate -path ./migrations -database "postgres://postgres:123456@localhost:5432/moduleservice_db?sslmode=disable" up

migrate-dev-down:
	migrate -path ./migrations -database "postgres://postgres:123456@localhost:5432/moduleservice_db?sslmode=disable" down

migrate-dev-reset:
	migrate -path ./migrations -database "postgres://postgres:123456@localhost:5432/moduleservice_db?sslmode=disable" reset

migrate-dev-drop:
	migrate -path ./migrations -database "postgres://postgres:123456@localhost:5432/moduleservice_db?sslmode=disable" drop

migrate-dev-create:
	migrate create -ext sql -dir ./migrations -seq $(name)

dev-docker-drop-db:
	docker exec -it postgres_container dropdb --force -U postgres moduleservice_db

dev-docker-create-db:
	docker exec -it postgres_container createdb -U postgres moduleservice_db

dev-create-db:
	createdb -U postgres moduleservice_db

dev-drop-db:
	dropdb -U postgres moduleservice_db

build:
	go build -o app cmd/main.go

run:
	go run cmd/main.go